spring.application.name=site4-role-test
server.port=38084

#thymeleaf
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true
spring.thymeleaf.cache=false


#keycloak
spring.security.oauth2.client.registration.keycloak.client-id=role-test-site1
spring.security.oauth2.client.registration.keycloak.client-secret=mhW7OJnvtX0Els5qcOJjRQsP0Ca1eZrM
spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.keycloak.issuer-uri=https://www.kingkongapps.kr:30000/realms/ROLE-TEST
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://www.kingkongapps.kr:30000/realms/ROLE-TEST
appl.url=https://www.kingkongapps.kr:38084
site.url1=https://www.kingkongapps.kr:38084
site.url2=https://www.kingkongapps.kr:38085
site.url3=https://www.kingkongapps.kr:38086

# SSL
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-alias=kingkong

#Redis
spring.redis.host=localhost
spring.redis.port=6379
